<?xml version="1.0" ?>
<robot name="wagon" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find wagon_description)/urdf/common_properties.xacro"/>
  <xacro:property name="height" value="0.294" />
  <xacro:property name="hydrolic_offset" value="0.085" />


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.6948 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="$(find wagon_description)/meshes/bases/Simplified_Front_Centered.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="-${0.6948-(1.055/2)+0.02} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.055 0.620 0.260"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="-0.142 0 0" rpy="0 0 0" />
      <mass value="7.5" />
      <inertia ixx="4.806e-2"
               ixy="0.0" iyy="1.193e-1"
               ixz="0.0" iyz="0.0" izz="1.493e-1" />
    </inertial>
  </link>

  <joint name="hydrolic_joint" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-0.550" upper="0.550" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="${-0.6948-hydrolic_offset} 0.0 0"/>
    <parent link="base_link"/>
    <child link="hydrolic_link"/>
  </joint>

  <link name="hydrolic_link">
    </link>

  <joint name="rear_joint" type="fixed">
    <parent link="hydrolic_link"/>
    <child link="rear_link"/>
    <origin xyz="${-0.8716+hydrolic_offset} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="rear_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 1.57"/>
        <geometry>
        <mesh filename="$(find wagon_description)/meshes/bases/Simplified_Back_Centered.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>
<!-- ${-0.8716+hydrolic_offset-(1.180/2)+0.02} -->
<!-- ${(1.180/2) + 0.8716+hydrolic_offset+0.02-1.180} -->
    <collision>
        <origin xyz="${0.09} 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${1.02} 0.620 0.260"/>
        </geometry>
    </collision>

    <inertial>
        <origin xyz="-0.142 0 0" rpy="0 0 0" />
        <mass value="7.5" />
        <inertia ixx="4.806e-2"
                ixy="0.0" iyy="1.193e-1"
                ixz="0.0" iyz="0.0" izz="1.493e-1" />
    </inertial>
  </link>



  <joint name="wheel_front_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_right_link"/>
    <origin xyz="0 -0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_front_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find wagon_description)/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.292"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="1.525" />
      <inertia ixx="6.723e-3"
               ixy="0.0" iyy="6.723e-3"
               ixz="0.0" iyz="0.0" izz="1.220e-2" />
    </inertial>
  </link>

    <joint name="wheel_front_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_left_link"/>
    <origin xyz="0 0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_front_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find wagon_description)/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="1.525" />
      <inertia ixx="6.723e-3"
               ixy="0.0" iyy="6.723e-3"
               ixz="0.0" iyz="0.0" izz="1.220e-2" />
    </inertial>
  </link>

    <joint name="wheel_rear_right_joint" type="continuous">
    <parent link="rear_link"/>
    <child link="wheel_rear_right_link"/>
    <origin xyz="0 -0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_rear_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find wagon_description)/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="1.525" />
      <inertia ixx="6.723e-3"
               ixy="0.0" iyy="6.723e-3"
               ixz="0.0" iyz="0.0" izz="1.220e-2" />
    </inertial>
  </link>

    <joint name="wheel_rear_left_joint" type="continuous">
    <parent link="rear_link"/>
    <child link="wheel_rear_left_link"/>
    <origin xyz="0 0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_rear_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find wagon_description)/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="1.525" />
      <inertia ixx="6.723e-3"
               ixy="0.0" iyy="6.723e-3"
               ixz="0.0" iyz="0.0" izz="1.220e-2" />
    </inertial>
  </link>

</robot>