<?xml version="1.0" ?>
<robot name="wagon" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find wagon_description)/urdf/common_properties.xacro"/>
  <xacro:property name="height" value="0.294" />
  <xacro:property name="hydraulic_offset" value="0.085" />
  <xacro:property name="rear_link_offset" value="-0.8716" />
  <xacro:property name="base_link_offset" value="0.6948" />


<!-- 
  <link name="base_footprint">
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.6948 0 0" rpy="0 0 0"/>
  </joint> -->

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/bases/Simplified_Front_Centered.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="-${base_link_offset-(1.055/2)+0.02} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.055 0.620 0.260"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="-0.142 0 0" rpy="0 ${pi/2} 0" />
      <mass value="185.5" />
      <inertia ixx="6.189"
               ixy="0" iyy="17.997"
               ixz="-0.009" iyz="0" izz="21.229" />
    </inertial>
  </link>

  <joint name="connection_joint" type="revolute">

    <parent link="base_link"/>
    <child link="connection_link"/>
    <origin xyz="${rear_link_offset + hydraulic_offset} 0 0" rpy="0 0 0"/>
    <axis xyz='1 0 0'/>
    <limit effort="1000.0" lower="-0.350" upper="0.350" velocity="0.5"/>

  </joint>

  <link name="connection_link">
    </link>

  
    
  <joint name="hydraulic_joint" type="revolute">
    <axis xyz="0 0 -1"/>
    <limit effort="1000.0" lower="-0.80" upper="0.80" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0"/>
    <parent link="connection_link"/>
    <child link="hydraulic_link"/>
  </joint>

  <link name="hydraulic_link">
    </link>

  <joint name="rear_joint" type="fixed">
    <parent link="hydraulic_link"/>
    <child link="rear_link"/>
    <origin xyz="${-0.8716+hydraulic_offset} 0 0" rpy="0 0 0"/>
      <axis xyz='1 1 0'/>

  </joint>

 
  <link name="rear_link">
    <visual>
        <geometry>
        <mesh filename="package://wagon_description/meshes/bases/Simplified_Back_Centered.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>

    </visual>
<!-- ${-0.8716+hydraulic_offset-(1.180/2)+0.02} -->
<!-- ${(1.180/2) + 0.8716+hydraulic_offset+0.02-1.180} -->
    <collision>
        <origin xyz="${hydraulic_offset} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${1.02} 0.620 0.260"/>
        </geometry>
    </collision>

    <inertial>
        <origin xyz="${0.142} 0 0" rpy="0 0 0" />
        <mass value="190.5" />
      <inertia ixx="6.189"
               ixy="0" iyy="17.997"
               ixz="-0.009" iyz="0" izz="21.229" />
    </inertial>
  </link>



  <joint name="wheel_front_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_right_link"/>
    <origin xyz="0 -0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_front_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.292"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="40.5" />
      <inertia ixx="1.05"
               ixy="1.0783e-10" iyy="1.83"
               ixz="-0.023" iyz="-0.898e-11" izz="1.05" />
    </inertial>
  </link>

    <joint name="wheel_front_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_left_link"/>
    <origin xyz="0 0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_front_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="40.5" />
      <inertia ixx="1.05"
               ixy="1.0783e-10" iyy="1.83"
               ixz="-0.023" iyz="-0.898e-11" izz="1.05" />
    </inertial>
  </link>

  <joint name="wheel_rear_right_joint" type="continuous">
    <parent link="rear_link"/>
    <child link="wheel_rear_right_link"/>
    <origin xyz="0 -0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_rear_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="40.5" />
      <inertia ixx="1.05"
               ixy="1.0783e-10" iyy="1.83"
               ixz="-0.023" iyz="-0.898e-11" izz="1.05" />
    </inertial>
  </link>

    <joint name="wheel_rear_left_joint" type="continuous">
    <parent link="rear_link"/>
    <child link="wheel_rear_left_link"/>
    <origin xyz="0 0.4815 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="wheel_rear_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/wheels/Wheel.stl" scale="0.001 0.001 0.001"/>
      <!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.07" radius="0.12"/>
        -->
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="0.215" radius="0.294"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <mass value="40.5" />
      <inertia ixx="1.05"
               ixy="1.0783e-10" iyy="1.83"
               ixz="-0.023" iyz="-0.898e-11" izz="1.05" />
    </inertial>
  </link>


  <joint name="imu_joint" type="fixed">
    <parent link="rear_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.272" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 -0.036" rpy="${pi/2} 0 0"/>
      <geometry>
        <mesh filename="package://wagon_description/meshes/sensors/ouster_OS1.dae" scale="1 1 1"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.072" radius="0.079"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.314" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <xacro:property name="rtk_pole_height" value="0.28" />


  <joint name="rtk_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rtk_pole"/>
    <origin xyz="-0.200 0 ${0.142+rtk_pole_height}" rpy="0 0 0"/>
  </joint>

  <link name="rtk_pole">
    <visual>
      <origin xyz="0 0 -${rtk_pole_height/2}" rpy="0 0 0"/>
      <geometry>
        <!-- <mesh filename="package://wagon_description/meshes/sensors/rtk.dae" scale="1 1 1"/> -->
        <cylinder length="${rtk_pole_height}" radius="0.01"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 -${rtk_pole_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${rtk_pole_height}" radius="0.01"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.314" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>


</robot>